"""PDF export for legal drafts."""

import tempfile
from pathlib import Path

from fpdf import FPDF


def generate_pdf(draft_text: str, title: str = "Nyay Mitra - Legal Draft") -> str:
    """Render draft text to a downloadable PDF. Returns file path."""
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, title, ln=True, align="C")
    pdf.ln(5)

    pdf.set_font("Helvetica", size=11)
    for line in draft_text.split("\n"):
        line = line.strip()
        if line:
            pdf.multi_cell(0, 7, line)
        else:
            pdf.ln(4)

    pdf.ln(8)
    pdf.set_font("Helvetica", "I", 8)
    pdf.multi_cell(
        0,
        5,
        "DISCLAIMER: This document was generated by Nyay Mitra AI. "
        "It is not legal advice. Please consult a qualified lawyer before taking any legal action.",
    )

    out = Path(tempfile.gettempdir()) / "nyay_mitra_draft.pdf"
    pdf.output(str(out))
    return str(out)
